name: Canary for multi-turn

on: [workflow_dispatch, push, pull_request]

jobs:

  canary-multi-turn:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        model:
          - mistralai/mistral-7b-instruct-v0.3           # $0.07 [ 32K]
          - qwen/qwen-2-7b-instruct                      # $0.07 [ 32K]
          - meta-llama/llama-3.1-8b-instruct             # $0.09 [128K]
          - microsoft/phi-3-medium-4k-instruct           # $0.14 [  4K]
          - nousresearch/hermes-2-pro-llama-3-8b         # $0.15 [  8K]
          - mistralai/mistral-nemo                       # $0.18 [128K]
          - mistralai/mixtral-8x7b-instruct              # $0.24 [ 32K]
          - google/gemma-2-27b-it                        # $0.27 [  4K]
          - openai/gpt-4o-mini                           # $0.15/$0.60 [ 128K]
          - meta-llama/llama-3.1-70b-instruct            # $0.52/$0.75 [ 128K]
    steps:
      - uses: actions/checkout@v4

      - run: ./query-llm.js tests/canary-single-turn.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - run: ./query-llm.js tests/canary-multi-turn.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
