name: General Knowledge

on: [workflow_dispatch, push, pull_request]

jobs:

  general-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        model:
          - qwen/qwen-2-7b-instruct                      # $0.0540/$0.0540 [  32K]
          - mistralai/mistral-7b-instruct-v0.3           # $0.0550/$0.0550 [  32K]
          - meta-llama/llama-3.1-8b-instruct             # $0.0550/$0.0550 [ 128K]
          - mistralai/ministral-8b-instruct              # $0.1000/$0.1000 [ 128K]
          - microsoft/phi-3.5-mini-128k-instruct         # $0.1000/$0.1000 [ 128K]
          - mistralai/mistral-nemo                       # $0.1300/$0.1300 [ 128K]
          - mistralai/mixtral-8x7b-instruct              # $0.2400/$0.2400 [  32K]
          - ai21/jamba-1-5-mini                          # $0.2000/$0.4000 [ 256K]
          - openai/gpt-4o-mini                           # $0.1500/$0.6000 [ 128K]
    steps:
      - uses: actions/checkout@v4

      - run: ./query-llm.js tests/canary-single-turn.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - run: ./query-llm.js tests/general-knowledge.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
