name: General Knowledge

on: [workflow_dispatch, push, pull_request]

jobs:

  general-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        model:
          - mistralai/mistral-7b-instruct-v0.3           # $0.0550/$0.0550 [  32K]
          - meta-llama/llama-3.2-11b-vision-instruct     # $0.0550/$0.0550 [ 128K]
          - mistralai/mistral-nemo                       # $0.1300/$0.1300 [ 128K]
          - google/gemini-flash-1.5-8b                   # $0.0375/$0.1500 [1000K]
          - amazon/nova-lite-v1                          # $0.0600/$0.2400 [ 300K]
          - qwen/qwen-2.5-7b-instruct                    # $0.2700/$0.2700 [ 128K]
          - google/gemini-flash-1.5                      # $0.0750/$0.3000 [1000K]
          - meta-llama/llama-3.3-70b-instruct            # $0.1300/$0.4000 [ 128K]
          - openai/gpt-4o-mini                           # $0.1500/$0.6000 [ 128K]
    steps:
      - uses: actions/checkout@v4

      - run: ./query-llm.js tests/canary-single-turn.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - run: ./query-llm.js tests/general-knowledge.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
